server {
    listen 80;
    server_name _;
    root /var/www/lbog/src;
    charset utf-8;

    location = / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    }

    location /uploads/ {
        return 404;
    }

    location / {
        try_files $uri @php;
    }

    location @php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$uri.php;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    }

    location ~ \.php$ {
        return 404;
    }
}
